// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.clubmanagementsystem.app.domain;

import com.clubmanagementsystem.app.domain.LadiesDrink;
import org.springframework.data.annotation.Persistent;

privileged aspect LadiesDrink_Roo_Mongo_Entity {
    
    declare @type: LadiesDrink: @Persistent;
    
}
