// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.clubmanagementsystem.app.domain;

import com.clubmanagementsystem.app.domain.Lady;

privileged aspect Lady_Roo_JavaBean {
    
    public String Lady.getName() {
        return this.name;
    }
    
    public void Lady.setName(String name) {
        this.name = name;
    }
    
}
