// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.clubmanagementsystem.app.domain;

import com.clubmanagementsystem.app.domain.Stock;

privileged aspect Stock_Roo_JavaBean {
    
    public String Stock.getName() {
        return this.name;
    }
    
    public void Stock.setName(String name) {
        this.name = name;
    }
    
}
