// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.clubmanagementsystem.app.domain;

import com.clubmanagementsystem.app.domain.WaiterIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect WaiterIntegrationTest_Roo_Configurable {
    
    declare @type: WaiterIntegrationTest: @Configurable;
    
}
